version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: teampulse-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123!
      MYSQL_DATABASE: teampulse
      MYSQL_USER: teampulse_user
      MYSQL_PASSWORD: teampulse123!
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: teampulse-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: teampulse_user
      DB_PASSWORD: teampulse123!
      DB_NAME: teampulse
      JWT_SECRET: your-secret-key-here
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  mysql_data: